### ISSUE TITLE
Errors trying to run examples

### ISSUE THREAD

**Issue by jonathanstrong** [SergejJurecko/mio_httpc#1]
Hey, 

I tried to run the examples and received the following errors: 

```console
$ RUST_BACKTRACE=1 cargo run --example get --features native -- "https://edition.cnn.com"
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/get 'https://edition.cnn.com'`
thread 'main' panicked at 'Call failed: Io(Error { repr: Os { code: 17, message: "File exists" } })', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17h6b0e028b9e47eeccE.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h5c0ea1fecbcb832fE.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: _ZN3std9panicking11begin_panic17hd62d509897a218a3E.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:799
  11: get::main
             at examples/get.rs:32
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```
Same error for websockets example. For streaming, got this: 

```console
$ RUST_BACKTRACE=1 cargo run --example get_streaming --features native -- "https://edition.cnn.com"
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/get_streaming 'https://edition.cnn.com'`
thread 'main' panicked at 'Failed while sending entity already exists', examples/get_streaming.rs:34:24
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17h6b0e028b9e47eeccE.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h5c0ea1fecbcb832fE.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: _ZN3std9panicking11begin_panic17hd62d509897a218a3E.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: get_streaming::main
             at examples/get_streaming.rs:34
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  10: main
  11: __libc_start_main
  12: _start
```

**Comment by SergejJurecko** [comment]
try now.

**Comment by jonathanstrong** [comment]
Yes, the changes in 4e84620 resolved the errors. 

This is working for most sites I try but some return "No response" - could this be a http 2 issue? In all likelihood this won't be a problem for my actual use case but want to figure out what the issue is. 

One additional question (networking is not my area of expertise, so may not be a good one): does this library deal with or feature http keep-alive? I honestly don't know how it even works but have been told this is a major factor in request latency. 

Glad I was able to find this library from the reddit thread and look forward to checking it out further.

**Comment by SergejJurecko** [comment]
Give me the address of websites that don't seem to work.

Keep-alive is next on the todo list and should be done this/next week.

**Comment by SergejJurecko** [comment]
Done, published to crates and a bug when trying to open multiple calls was fixed.
